map('n', '<C-p>', "<cmd>lua require('telescope.builtin').find_files()<cr>")
map('n', 'F', "<cmd>lua require('telescope.builtin').find_files()<cr>")
map('n', 'G', "<cmd>lua require('telescope.builtin').live_grep()<cr>")
map('n', 'B', "<cmd>lua require('telescope.builtin').buffers()<cr>")
map('n', 'H', "<cmd>lua require('telescope.builtin').help_tags()<cr>")

map('n', 'd', "<cmd>lua require('telescope.builtin').lsp_definitions()<cr>")
map('n', 'r', "<cmd>lua require('telescope.builtin').lsp_references()<cr>")
map('n', '<leader>ca', "<cmd>lua require('telescope.builtin').lsp_code_actions()<cr>")
map('n', '<leader>ds', "<cmd>lua require('telescope.builtin').lsp_document_symbols()<cr>")
map('n', '<leader>ws', "<cmd>lua require('telescope.builtin').lsp_workspace_symbols()<cr>")
