#!/bin/bash
PAPE=$(basename $1) &&
wpg -a $1 &&
wpg -A $PAPE &&
SCHEME=$(ls /home/lmlorca/.config/wpg/schemes | grep $PAPE) &&
# wal --theme /home/lmlorca/.config/wpg/schemes/$SCHEME -b '#1e1e1e' &&
wal --theme /home/lmlorca/.config/wpg/schemes/$SCHEME -s -t -b '#1e1e1e' &&
feh --bg-fill $PAPE &&
# /home/lmlorca/.scripts/dark-theme.sh &&
# /home/lmlorca/.scripts/reload-gtk.sh &&
notify-send "Wallpaper and Theme updated" $PAPE
